Name: customadmin
After:
  - '#adminroutes'
---
SilverStripe\Admin\AdminRootController:
  url_base: 'backend-login-access-page'
SilverStripe\Control\Director:
  rules:
    'admin': 'Local\Blocks\CustomAdminController'
    'backend-login-access-page': 'SilverStripe\Admin\AdminRootController'
